const defaultTeams=[
{name:'1M Academy',tag:'1MA',country:'Russia',status:'active',rank:1,matches:28,wins:22,points:2140,logo:'',faceit:'https://www.faceit.com/',steam:'https://steamcommunity.com/',description:'Молодой состав 1Minute, который строится вокруг дисциплины и стабильной игры.'},
{name:'Velocity',tag:'VL',country:'Netherlands',status:'active',rank:2,matches:27,wins:20,points:2070,logo:'',faceit:'https://www.faceit.com/',steam:'https://steamcommunity.com/',description:'Состав с агрессивным стилем и быстрым темпом.'},
{name:'NightFox',tag:'NF',country:'Germany',status:'active',rank:3,matches:30,wins:19,points:1985,logo:'',faceit:'https://www.faceit.com/',steam:'https://steamcommunity.com/',description:'Тактическая команда с упором на командную игру.'},
{name:'Rebels',tag:'RB',country:'Poland',status:'active',rank:4,matches:25,wins:17,points:1910,logo:'',faceit:'https://www.faceit.com/',steam:'https://steamcommunity.com/',description:'Молодой конкурентоспособный состав.'},
{name:'Nova',tag:'NV',country:'Sweden',status:'inactive',rank:5,matches:22,wins:12,points:1760,logo:'',faceit:'',steam:'',description:'Команда временно неактивна.'},
{name:'United',tag:'UN',country:'France',status:'inactive',rank:6,matches:20,wins:9,points:1640,logo:'',faceit:'',steam:'',description:'Состав находится на перерыве.'}
];
let teams=JSON.parse(localStorage.getItem('1minute-teams')||'null')||defaultTeams;
const matches=[['1M Academy','Velocity','16 : 12','Сегодня'],['NightFox','Rebels','13 : 16','Вчера'],['Nova','United','10 : 16','16.08.2026'],['Velocity','NightFox','16 : 14','15.08.2026']];
const tournaments=[['1Minute Championship #12','Активный','128 команд'],['1Minute Pro League S4','Активный','32 команды'],['1Minute Cup Summer','Завершён','64 команды']];
const teamPlayers={
'1M Academy':['s1mple','electroNic','b1t','Perfecto','Ax1Le'],'Velocity':['m0NESY','NiKo','huNter-','jks','malbsMd'],'NightFox':['donk','sh1ro','magixx','zont1x','chopper'],'Rebels':['ZywOo','apEX','flameZ','mezii','ropz'],'Nova':['rain','broky','karrigan','frozen','Jame'],'United':['device','stavn','jabbi','cadiaN','dupreeh']};
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function logo(t,cls='team-logo'){return t.logo?`<div class="${cls}"><img src="${esc(t.logo)}" alt=""></div>`:`<div class="${cls}">${esc(t.tag)}</div>`}
function renderTeams(list){document.getElementById('grid').innerHTML=list.map(t=>`<article class="team-card" onclick="openTeam('${esc(t.name)}')"><div class="team-top">${logo(t)}<div><div class="team-name">${esc(t.name)}</div><div class="team-country">◉ ${esc(t.country)}</div></div></div><div class="team-bottom"><span>#${t.rank} · ${t.points} ELO</span><span class="status ${t.status}">${t.status==='active'?'ACTIVE':'INACTIVE'}</span></div></article>`).join('')}
function filterTeams(type,btn){document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');renderTeams(type==='all'?teams:teams.filter(t=>t.status===type))}
function renderAll(){renderTeams(teams);document.getElementById('ratingRows').innerHTML=teams.map(t=>`<tr><td>#${t.rank}</td><td><b>${esc(t.name)}</b></td><td>${t.matches}</td><td>${t.wins}</td><td><b>${t.points}</b></td></tr>`).join('');document.getElementById('matchesList').innerHTML=matches.map(m=>`<div class="match"><div><div class="match-name">${esc(m[0])} — ${esc(m[1])}</div><div class="date">${m[3]}</div></div><div class="score">${m[2]}</div></div>`).join('');document.getElementById('tournamentsGrid').innerHTML=tournaments.map(t=>`<div class="tournament"><span class="status">${t[1]}</span><h3>${t[0]}</h3><p>${t[2]} · 1Minute</p></div>`).join('')}
renderAll();
function openTeam(name){const t=teams.find(x=>x.name===name);if(!t)return;document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));document.getElementById('teamPage').classList.remove('hidden');const players=teamPlayers[name]||['PlayerOne','PlayerTwo','PlayerThree','PlayerFour','PlayerFive'];document.getElementById('teamProfile').innerHTML=`<div class="profile"><div class="profile-hero"><div class="profile-top">${logo(t,'profile-logo')}<div><h1>${esc(t.name)}</h1><div class="profile-country">◉ ${esc(t.country)} · ${t.status==='active'?'Активная команда':'Неактивная команда'}</div><div class="links">${t.faceit?`<a class="link" target="_blank" href="${esc(t.faceit)}">FACEIT ↗</a>`:''}${t.steam?`<a class="link" target="_blank" href="${esc(t.steam)}">Steam ↗</a>`:''}</div></div></div><div class="profile-stats"><div class="stat"><b>#${t.rank}</b><small>Место</small></div><div class="stat"><b>${t.points}</b><small>ELO</small></div><div class="stat"><b>${t.matches}</b><small>Матчей</small></div><div class="stat"><b>${Math.round(t.wins/t.matches*100)}%</b><small>Win rate</small></div></div><div class="panel-actions"><button class="edit-btn" onclick="openEditor('${esc(t.name)}')">✎ Редактировать профиль</button></div></div><div class="profile-grid"><div class="panel"><h3>Состав</h3>${players.map((p,i)=>`<div class="player"><div class="mini">${p.slice(0,2).toUpperCase()}</div><div><b>${esc(p)}</b><div class="role">${i===0?'Капитан':'Игрок'}</div></div></div>`).join('')}</div><div class="panel"><h3>О команде</h3><p style="color:#858c98;line-height:1.7;font-size:13px">${esc(t.description)}</p><div class="date">Победы: ${t.wins} · Поражения: ${t.matches-t.wins}</div></div></div></div>`;location.hash='team/'+encodeURIComponent(name);window.scrollTo(0,0)}
function closeTeam(){document.getElementById('teamPage').classList.add('hidden');document.querySelectorAll('.screen').forEach(x=>x.classList.remove('hidden'));location.hash='teams';window.scrollTo(0,0)}
function openEditor(name){const t=teams.find(x=>x.name===name);if(!t)return;document.getElementById('editName').value=t.name;document.getElementById('editTitle').value=t.name;document.getElementById('editTag').value=t.tag;document.getElementById('editCountry').value=t.country;document.getElementById('editLogo').value=t.logo||'';document.getElementById('editFaceit').value=t.faceit||'';document.getElementById('editSteam').value=t.steam||'';document.getElementById('editDescription').value=t.description||'';document.getElementById('editModal').classList.remove('hidden')}
function closeEditor(){document.getElementById('editModal').classList.add('hidden')}
document.getElementById('editForm').addEventListener('submit',e=>{e.preventDefault();const old=document.getElementById('editName').value;const t=teams.find(x=>x.name===old);if(!t)return;t.name=document.getElementById('editTitle').value.trim();t.tag=document.getElementById('editTag').value.trim().toUpperCase();t.country=document.getElementById('editCountry').value.trim();t.logo=document.getElementById('editLogo').value.trim();t.faceit=document.getElementById('editFaceit').value.trim();t.steam=document.getElementById('editSteam').value.trim();t.description=document.getElementById('editDescription').value.trim();localStorage.setItem('1minute-teams',JSON.stringify(teams));closeEditor();openTeam(t.name);renderAll()});
window.addEventListener('hashchange',()=>{const h=decodeURIComponent(location.hash.slice(1));if(h.startsWith('team/'))openTeam(h.slice(5));});
