const teams = [
{name:"1M Academy",tag:"1MA",country:"Russia",status:"active",rank:1,matches:28,wins:22,points:2140,faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/",description:"Молодой состав 1Minute, который строится вокруг дисциплины и стабильной игры."},
{name:"Velocity",tag:"VL",country:"Netherlands",status:"active",rank:2,matches:27,wins:20,points:2070,faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/",description:"Состав с агрессивным стилем и быстрым темпом."},
{name:"NightFox",tag:"NF",country:"Germany",status:"active",rank:3,matches:30,wins:19,points:1985,faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/",description:"Тактическая команда с упором на командную игру."}
];

const defaultPlayers={"1M Academy":[{name:"s1mple",country:"Russia",role:"Капитан",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"},{name:"electroNic",country:"Russia",role:"Rifler",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"},{name:"b1t",country:"Ukraine",role:"Rifler",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"},{name:"Perfecto",country:"Russia",role:"Support",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"},{name:"Ax1Le",country:"Russia",role:"Rifler",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"}],"Velocity":[{name:"m0NESY",country:"Russia",role:"AWPer",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"},{name:"NiKo",country:"Bosnia",role:"Rifler",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"},{name:"huNter-",country:"Bosnia",role:"Rifler",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"},{name:"jks",country:"Australia",role:"Rifler",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"},{name:"malbsMd",country:"Guatemala",role:"Rifler",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"}],"NightFox":[{name:"donk",country:"Russia",role:"Rifler",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"},{name:"sh1ro",country:"Russia",role:"AWPer",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"},{name:"magixx",country:"Russia",role:"Rifler",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"},{name:"zont1x",country:"Russia",role:"Rifler",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"},{name:"chopper",country:"Russia",role:"IGL",avatar:"",faceit:"https://www.faceit.com/",steam:"https://steamcommunity.com/"}]};
let players=JSON.parse(localStorage.getItem("1minute-players")||"null")||defaultPlayers;
function esc(v){return String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function renderTeams(list=teams){const grid=document.getElementById("grid");if(!grid)return;grid.innerHTML=list.map(t=>`<article class="team-card" onclick="openTeam('${esc(t.name)}')"><div class="team-top"><div class="team-logo">${esc(t.tag)}</div><div><div class="team-name">${esc(t.name)}</div><div class="team-country">◉ ${esc(t.country)}</div></div></div><div class="team-bottom"><span>#${t.rank} · ${t.points} ELO</span><span class="status ${t.status}">${t.status==='active'?'ACTIVE':'INACTIVE'}</span></div></article>`).join("");}
function filterTeams(type,btn){document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("selected"));btn.classList.add("selected");renderTeams(type==='all'?teams:teams.filter(t=>t.status===type));}
function openTeam(name){const t=teams.find(x=>x.name===name);if(!t)return;document.querySelectorAll(".screen").forEach(x=>x.classList.add("hidden"));document.getElementById("teamPage").classList.remove("hidden");const list=players[name]||[];document.getElementById("teamProfile").innerHTML=`<div class="profile"><div class="profile-hero"><div class="profile-top"><div class="profile-logo">${esc(t.tag)}</div><div><h1>${esc(t.name)}</h1><div class="profile-country">◉ ${esc(t.country)} · ${t.status==='active'?'Активная команда':'Неактивная команда'}</div><div class="links"><a class="link" target="_blank" href="${esc(t.faceit)}">FACEIT ↗</a><a class="link" target="_blank" href="${esc(t.steam)}">Steam ↗</a></div></div></div><div class="profile-stats"><div class="stat"><b>#${t.rank}</b><small>Место</small></div><div class="stat"><b>${t.points}</b><small>ELO</small></div><div class="stat"><b>${t.matches}</b><small>Матчей</small></div><div class="stat"><b>${Math.round(t.wins/t.matches*100)}%</b><small>Win rate</small></div></div></div><div class="profile-grid"><div class="panel"><h3>Состав</h3>${list.map(p=>`<div class="player" onclick="openPlayer('${esc(t.name)}','${esc(p.name)}')" style="cursor:pointer"><div class="mini">${p.avatar?`<img src="${esc(p.avatar)}" style="width:100%;height:100%;object-fit:cover;border-radius:8px">`:esc(p.name.slice(0,2).toUpperCase())}</div><div><b>${esc(p.name)}</b><div class="role">${esc(p.role)}</div></div></div>`).join("")}</div><div class="panel"><h3>О команде</h3><p style="color:#858c98;line-height:1.7;font-size:13px">${esc(t.description)}</p><div class="date">Победы: ${t.wins} · Поражения: ${t.matches-t.wins}</div></div></div></div>`;location.hash='team/'+encodeURIComponent(name);window.scrollTo(0,0);}
function closeTeam(){document.querySelectorAll(".screen").forEach(x=>x.classList.add("hidden"));document.getElementById("teams").classList.remove("hidden");location.hash='teams';window.scrollTo(0,0);}
function openPlayer(teamName,playerName){const t=teams.find(x=>x.name===teamName),list=players[teamName]||[],p=list.find(x=>x.name===playerName);if(!t||!p)return;document.querySelectorAll(".screen").forEach(x=>x.classList.add("hidden"));document.getElementById("playerPage").classList.remove("hidden");document.getElementById("playerProfile").innerHTML=`<div class="profile"><div class="profile-hero"><div class="profile-top"><div class="profile-logo">${p.avatar?`<img src="${esc(p.avatar)}" style="width:100%;height:100%;object-fit:cover;border-radius:16px">`:esc(p.name.slice(0,2).toUpperCase())}</div><div><h1>${esc(p.name)}</h1><div class="profile-country">◉ ${esc(p.country)}</div><div class="role">${esc(p.role)}</div><div class="links">${p.faceit?`<a class="link" target="_blank" href="${esc(p.faceit)}">FACEIT ↗</a>`:''}${p.steam?`<a class="link" target="_blank" href="${esc(p.steam)}">Steam ↗</a>`:''}</div><div style="margin-top:16px"><button class="edit-btn" onclick="openPlayerEditor('${esc(t.name)}','${esc(p.name)}')">✎ Редактировать профиль</button></div></div></div><div class="profile-stats"><div class="stat"><b>${esc(t.name)}</b><small>Команда</small></div><div class="stat"><b>${esc(p.role)}</b><small>Роль</small></div><div class="stat"><b>${esc(p.country)}</b><small>Страна</small></div><div class="stat"><b>CS2</b><small>Дисциплина</small></div></div></div><div class="profile-grid"><div class="panel"><h3>Профиль игрока</h3><p style="color:#858c98;line-height:1.8;font-size:13px">Никнейм: <b>${esc(p.name)}</b><br>Роль: <b>${esc(p.role)}</b><br>Страна: <b>${esc(p.country)}</b></p></div><div class="panel"><h3>Команда</h3><p style="color:#858c98;line-height:1.8;font-size:13px">${esc(t.name)}<br>${esc(t.country)}</p><button class="edit-btn" onclick="openTeam('${esc(t.name)}')">← Открыть команду</button></div></div></div>`;location.hash='player/'+encodeURIComponent(teamName)+'/'+encodeURIComponent(playerName);window.scrollTo(0,0);}
function openPlayerEditor(teamName,oldName){const list=players[teamName]||[],p=list.find(x=>x.name===oldName);if(!p)return;document.getElementById("playerEditModal")?.remove();const modal=document.createElement("div");modal.id="playerEditModal";modal.className="modal";modal.innerHTML=`<div class="modal-card"><button class="modal-close" onclick="closePlayerEditor()">×</button><div class="eyebrow">PLAYER EDITOR</div><h2>Редактировать игрока</h2><form id="playerEditForm"><label>Ник<input id="peName" value="${esc(p.name)}" required></label><label>Страна<input id="peCountry" value="${esc(p.country)}" required></label><label>Роль<input id="peRole" value="${esc(p.role)}" required></label><label>FACEIT URL<input id="peFaceit" value="${esc(p.faceit||"")}" placeholder="https://faceit.com/..."></label><label>Steam URL<input id="peSteam" value="${esc(p.steam||"")}" placeholder="https://steamcommunity.com/..."></label><label>Аватар URL<input id="peAvatar" value="${esc(p.avatar||"")}" placeholder="https://..."></label><div style="display:flex;gap:10px;margin-top:18px"><button class="primary save" type="submit">Сохранить</button><button class="edit-btn" type="button" onclick="closePlayerEditor()">Отмена</button></div></form></div>`;document.body.appendChild(modal);document.getElementById("playerEditForm").addEventListener("submit",e=>{e.preventDefault();p.name=document.getElementById("peName").value.trim();p.country=document.getElementById("peCountry").value.trim();p.role=document.getElementById("peRole").value.trim();p.faceit=document.getElementById("peFaceit").value.trim();p.steam=document.getElementById("peSteam").value.trim();p.avatar=document.getElementById("peAvatar").value.trim();localStorage.setItem("1minute-players",JSON.stringify(players));closePlayerEditor();openPlayer(teamName,p.name);});}
function closePlayerEditor(){const m=document.getElementById("playerEditModal");if(m)m.remove();}
function closePlayer(){const h=decodeURIComponent(location.hash.slice(1));if(h.startsWith('player/')){const parts=h.slice(7).split('/');if(parts[0])return openTeam(parts[0]);}closeTeam();}
function renderRating(){const r=document.getElementById("ratingRows");if(!r)return;r.innerHTML=teams.map(t=>`<tr><td>#${t.rank}</td><td><b>${esc(t.name)}</b></td><td>${t.matches}</td><td>${t.wins}</td><td><b>${t.points}</b></td></tr>`).join("");}
function renderMatches(){const b=document.getElementById("matchesList");if(!b)return;b.innerHTML=`<div class="match"><div><div class="match-name">1M Academy — Velocity</div><div class="date">Сегодня</div></div><div class="score">16 : 12</div></div><div class="match"><div><div class="match-name">NightFox — Rebels</div><div class="date">Вчера</div></div><div class="score">13 : 16</div></div>`;}
function renderTournaments(){const b=document.getElementById("tournamentsGrid");if(!b)return;b.innerHTML=`<div class="tournament"><span class="status">Активный</span><h3>1Minute Championship #12</h3><p>128 команд · 1Minute</p></div><div class="tournament"><span class="status">Активный</span><h3>1Minute Pro League S4</h3><p>32 команды · 1Minute</p></div>`;}
renderTeams();renderRating();renderMatches();renderTournaments();
window.addEventListener("hashchange",()=>{const h=decodeURIComponent(location.hash.slice(1));if(h.startsWith('player/')){const p=h.slice(7).split('/');if(p.length>=2)openPlayer(p[0],p[1]);return;}if(h.startsWith('team/'))openTeam(h.slice(5));});
